<a href="https://colab.research.google.com/github/YISHAN2021/ML100Days/blob/main/D02_NumPy_%E9%99%A3%E5%88%97%E9%80%B2%E9%9A%8E%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

題目:
>1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")

>2.呈上題的array，找出被6除餘1的數的索引

In [ ]:
import numpy as np
array1 = np.array(range(30)).reshape((5, -1))
print(array1,end="\n\n")
np.where(array1%6 == 1)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]



(array([0, 1, 2, 3, 4]), array([1, 1, 1, 1, 1]))